title: Bennett's Personal Website
description: Download resume, professional pic, etc. 
theme: just-the-docs

url: https://sheldonstudiosk112.github.io/website/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
